import Invoice from "@/components/assets/invoice";
import LinkInBio from "@/components/assets/link_in_bio";
import MediaKit from "@/components/assets/media_kit";
import Store from "@/components/assets/store";
import Nav from "@/components/common/nav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "react-day-picker/dist/style.css";
import "./globals.css";
import Providers from "./provider";

const inter = Inter({ subsets: ["latin"] });

const degular = localFont({
  src: [
    {
      path: "../public/font/Degular-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/Degular-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/Degular-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/font/Degular-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--degular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="py-4 relative">
        <Providers>
          <div className="fixed top-[310px] left-4 grid gap-6 px-3 py-4 rounded-[100px] bg-white shadow-[0px_6px_12px_0px_rgba(92,115,131,0.08),0px_4px_8px_0px_rgba(92,115,131,0.08)]">
            <div className="cursor-pointer">
              <LinkInBio />
            </div>
            <div className="cursor-pointer">
              <Store />
            </div>
            <div className="cursor-pointer">
              <MediaKit />
            </div>
            <div className="cursor-pointer">
              <Invoice />
            </div>
          </div>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
